### ISSUE TITLE
Not getting any servers in my haproxy.cfg

### ISSUE THREAD

**Issue by bryanlandia** [alecpm/opsworks-web-python#6]
When the number of instances per cpu set is less than 4, the math in haproxy.cfg.erb will not yield any server lines for the plone_instances backend.

See  http://github.com/alecpm/opsworks-web-python/plone_buildout/templates/default/haproxy.cfg.erb

**Comment by bryanlandia** [comment]
Proposed fix in  PR https://github.com/alecpm/opsworks-web-python/pull/7

**Comment by alecpm** [comment]
Merged
